config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cart/show'
  resources :shops , only: [:index, :show]
  resources :products
  resources :order_items
  resources :order
  resource :cart, only: [:show]
  resource :social, only: [:show]
  resources :success, only: [:index]
  resources :catering, only: [:index]

  root 'shops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal
    after_initialize :set_defaults
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP} 
    def subtotal
        order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
    end

    def set_defaults
        self.name ||= "John Doe"
        self.email ||= "johndoe@gmail.com"
        self.address ||= "1234 Road Dr"
        self.date ||= Date.today
    end

    private 

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    before_save :set_unit_price
    before_save :set_total
    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end

    def total
        unit_price * quantity
    end

    private

    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total * quantity
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
    has_many :flavors
    accepts_nested_attributes_for :flavors
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_gon, only: [:show]
  #after_action :refresh_page, only: [:show]
  def show
    @order = current_order
    puts @order.id
    if @order.id == nil
      flash[:notice] = 'Please add items to cart before viewing'
      redirect_to shops_path alert
    end   
    @order_items = current_order.order_items
    
    #gon.finalPrice = current_order.subtotal
  end

  private

  def set_gon
    gon.finalPrice = current_order.subtotal
    gon.url = ENV['sucessURL']
    gon.client_id = ENV['client_id']
  end
end

app/controllers/catering_controller.rb
class CateringController < ApplicationController
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

    def update
        current_order.update(order_params)
        redirect_to cart_path

    end

    private

    def order_params
        params.require(:order).permit(:name, :email, :address, :date)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    if current_user && current_user.admin?
    @products = Product.all
    else
    redirect_to new_user_session_url
    end
    
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :required_num, :active, :price, :image)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    puts session[:order_id]
    @products = Product.all
  end

  def show
    @order_item = current_order.order_items.new
    @product = Product.find(params[:id])
  end



  private

  
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController
    
    def show

    end
end

app/controllers/success_controller.rb
class SuccessController < ApplicationController
    after_action :remove_cart, only: [:index]
    def index
        @order = current_order
        @name = current_order.name
        @email = current_order.email
        @address = current_order.address
        @date = current_order.date
        gon.successRED = ENV['successred']
        OrderNotficationEmailMailer.notfication(@order, @name, @email, @address, @date).deliver
        OrderNotficationEmailMailer.notfication(@order, @name, ENV['gmail_username'], @address, @date).deliver
        
    end

    private

    def remove_cart
        current_order.order_items.delete_all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def current_order
        if !session[:order_id].nil?
            puts "existing session"
            Order.find(session[:order_id])
        else
            puts "New Order"
            Order.new
        end       
    end
    

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/catering_helper.rb
module CateringHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/success_helper.rb
module SuccessHelper
end

app/views/carts/_cart-item.html.erb
<head>
 
    <script type="text/javascript">
        if (window.location.href.substr(-2) !== '?r') {
            window.location = window.location.href + '?r';
        }  
    </script>  
    <script>
      const fundingSources = [
            paypal.FUNDING.PAYPAL
            ]

          for (const fundingSource of fundingSources) {
            const paypalButtonsComponent = paypal.Buttons({
              fundingSource: fundingSource,

              // optional styling for buttons
              // https://developer.paypal.com/docs/checkout/standard/customize/buttons-style-guide/
              style: {
                shape: 'pill',
                height: 40,
                color: 'black',
                label: 'buynow'
              },

              // set up the transaction
              createOrder: (data, actions) => {
                // pass in any options from the v2 orders create call:
                // https://developer.paypal.com/api/orders/v2/#orders-create-request-body
                const createOrderPayload = {
                  purchase_units: [
                    {
                      amount: {
                        value: gon.finalPrice,
                      },
                    },
                  ],
                }
                return actions.order.create(createOrderPayload)
              },

              // finalize the transaction
              onApprove: (data, actions) => {
                const captureOrderHandler = (details) => {
                  const payerName = details.payer.name.given_name
                  console.log('Transaction completed!')
                  window.location.replace(gon.url)
                  //OrderNotficationEmailMailer.notification
                }
                
                return actions.order.capture().then(captureOrderHandler)
              },

              onCancel: (data, actions) => {
                const captureOrderHandler = (details) => {
                  const payerName = details.payer.name.given_name
                  console.log('Transaction Canceled')
                  window.location.replace("http://localhost:3000/social")
                  //OrderNotficationEmailMailer.notification
                }
                
                return actions.order.capture().then(captureOrderHandler)
              },

              // handle unrecoverable errors
              onError: (err) => {
                console.error(
                  'An error prevented the buyer from checking out with PayPal',
                )
                
              },
              
            })

            if (paypalButtonsComponent.isEligible()) {
              paypalButtonsComponent
                .render('#paypal-btn')
                .catch((err) => {
                  console.error('PayPal Buttons failed to render')
                })
            } else {
              console.log('The funding source is ineligible')
            }
          }
    </script>   
</head>
<body>
    <%= render 'info'%>
    <br>
    <div class = "cart-text center">Cart</div>
    <br>
    <% @order_items.each do |item| %>
        <div class = "cart-box">
            <div class="food-title"><%=item.product.title %></div>
            <div class="cart-text"><h5>$<%=number_with_precision(item.product.price, precision: 2) %></h3></div>

            <%= form_for item, remote: true do |f| %>
                <%f.hidden_field :product_id, :value => item.product.id %>
                <div class="quantity-box"><%=f.number_field :quantity, :value => item.quantity.to_i %></div>
                <%=f.submit "Update Cart", class: 'btn btn-secondary' %>
                <%=link_to "Remove Order Item", order_item_path(item), method: :delete, remote: true %>
            <%end %>
            <div class="cart-text"><h2>Subtotal: $<%=number_with_precision(item.total, precision: 2)%></h2></div>
            <%=image_tag(item.product.image, size: '260x180')%>
            <br>
            Note:<%=item.note %>
        </div>
    <br>
    <%end %>
    <br>
    <div class="cart-text center"><h1>Order Total: $<%=number_with_precision(current_order.subtotal, precision: 2) %></h1></div>
    <br>

    <div id="checkout"><%= render 'checkout'%></div>
</body>

app/views/carts/_cart.html.erb
<%= button_to "#{current_order.order_items.count} items at a total of #{number_with_precision(current_order.subtotal, precision: 2)}", cart_path, :method => :get, class: 'btn custom-btn' %>

app/views/carts/_checkout.html.erb
<div id="paypal-btn"></div>

app/views/carts/_info.html.erb
    <h3>Add a name, email, address and date to be associated with your order</h3>
    <%= form_for @order, remote: true do |f| %>
    <div class = "info-form">
        <%=f.label "Full Name", class: 'label-form' %>
        <%=f.text_field :name, value: @order.name, class: 'text-box'%>
    </div>
    <div class = "info-form">
        <%=f.label "Email Address", class: 'label-form' %>
        <%=f.email_field :email, value: @order.email, class: 'text-box'%>
    </div>
    <div class = "info-form">
        <%=f.label "Address", class: 'label-form' %>
        <%=f.text_field :address, value: @order.address, class: 'text-box'%>
    </div>
    <div class = "label-form">(Add NA if picking up)</div>
    <div class = "info-form">
        <%=f.label "Delivery/Pick-Up Date", class: 'label-form' %>
        <%=f.date_field :date, value: @order.date, class: 'text-box'%>
    </div>
    <br>
    <div class = "info-form">
        <%= f.submit "Update Information", class: 'btn custom-btn' %>
        </div>
    <%end %>

app/views/carts/show.html.erb
<head>
    
</head>
<div id="cart-item"><%= render 'cart-item'%></div>
<br>

app/views/catering/index.html.erb
<body>
    <h3>Page Coming Soon!</h3>
</body>

app/views/shops/index.html.erb
<h1 class = "center">Neesh'z Treat'z & Eat'z</h1>
  <body>
  <div id="cart">
    <%=render 'carts/cart' %>
  </div>
  <br>
  <div class = "grid-3-columns">
    <% @products.each do |product| %>
      <% if product.active == true %> 
        <div class = "item-box">    
            <div class = "food-title"><%= product.title %></div><br>
            <%=link_to image_tag(product.image, style:'height:60%; width:100%;'), shop_path(product) %><br>
            <div class = "food-title">$<%= number_with_precision(product.price, precision: 2)%></div><br>
            <div class = "food-description"><%=truncate(product.description, length: 20) %></div>
        </div>
      <% end %>
    <% end %>
  </div>
    
  </body>
<br>
<footer>
</footer>

app/views/shops/show.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Number of flavors required:</strong>
  <%= @product.required_num %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_with_precision(@product.price, precision: 2) %>
</p>

<%= link_to 'Back', root_path %> 
<%
=end%>

<body >
  <div id="cart">
    <%=render 'carts/cart' %>
  </div>
  <br>
  <div class = "show-grid">
    <div class = "center">
        <div class="item-show-title"><%= @product.title %></div><br>
        <%= image_tag(@product.image, class: 'show-image', style: 'transform: translate(-60px);')%><br>
    </div>
    <div class = "center">
        <div class = "item-show-description"><%= @product.description %></div><br>
        <div class = "item-show-title">$<%= number_with_precision(@product.price, precision: 2)%></div><br>
    <%= form_for @order_item, remote: true do |f| %> 
      <%=f.label "Order Note", class: "item-show-description" %>
      <%=f.text_area :note, style: "width:150%;transform: translate(-25px);"%>
      <br>
      <div class = "notice">*Use the Order Note box to list flavors wanted if applicable</div>
      <br>
      <%=f.hidden_field :product_id, :value => @product.id%>
      <%=f.number_field :quantity, :value => 1, :min => 1, style: 'width: 40%; display:inline;' %>
      <%=f.submit "Add to Cart", class: 'btn custom-btn', style: 'font-family: Georgia, serif; display:inline;transform: translate(-20px);'%>
    <%end %>
    </div>
  </div>
</body>

app/views/socials/show.html.erb
<body >
<div>
    <div class = "text-background social-text center"><h1>My Socials</h1></div><br>

    <div class = "column social-box">
        <h2>Instagram: </h2><a href="#">@NeeshzTreatz</a><br>
        <%= link_to image_tag("instagram.png", style: 'height:100%;width:100%;margin-right:50px;padding-right:20px;'), "https://www.instagram.com/NeeshzTreatz" %>
    </div> 
    <div class = "column social-box">
        <h2>TikTok: </h2><a href="#">@dneesha143</a><br>
        <%= link_to image_tag("tik-tok.png", style: 'height:100%;width:100%;margin-left:20px;padding-left:20px;'), "https://www.tiktok.com/t/ZTd7y8kJQ/"%>
    </div> 
</div>

<%
=begin%>
 <div class = "text-background social-text center">
    <p>Author: Antonio Daniels</p>
  <a href="mailto:tmitetime@gmail.com">tmitetime@gmail.com</a>
</div> 
<%
=end%>
</body>
<br>

app/views/success/index.html.erb
<head>
    <script>
        setTimeout(function() {
            window.location.replace(gon.successRED)
        }, 5000);
    </script>
</head>
<div class = "center success-s">
    Successful Transaction
</div>

app/views/success/show.html.erb
<h1>Show</h1>